In [2]:
#creating single dimensional array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)           #creating one dimensional array
print(a.dtype)     #finding the data type of array
print(a.ndim)      #finding the dimension of array
print(a[1])        #accesing the second element of the array
print(a[1]+a[3])   #accessing the second and fourth elements and adding 

[ 1  2  3  4  5  6  7  8  9 10]
int32
1
2
6


In [5]:
#print the index 1 to 5 
print(a[1:6])

[2 3 4 5 6]


In [6]:
#print from beginning to index 4
print(a[:5])

[1 2 3 4 5]


In [7]:
#print the value index3 from end to index one from end
print(a[-9:-6])

[2 3 4]


In [15]:
#slicing index 1 to index 5 and printing second element
print(a[1:6:5])

[2]


In [17]:
#creating 2 dim array
b=np.array([[24,25,26,27],[54,55,57,59]])
print(b)
print(b.ndim)

[[24 25 26 27]
 [54 55 57 59]]
2


In [19]:
print(b[0:1])
print(b[1:3])

[[24 25 26 27]]
[[54 55 57 59]]


In [25]:
print(a[1])   #accessing 2nd element in one dim

2


In [26]:
print(b[0,3])   #accessing 4th element in two dim

27


In [27]:
#creating three dimensions array
c=np.array([[[125,130,135],[140,145,150]],[[155,160,165],[170,175,180]]])
print(c)
print(c.ndim)

[[[125 130 135]
  [140 145 150]]

 [[155 160 165]
  [170 175 180]]]
3


In [30]:
#converting 1D into 2D
a=np.array([31,32,33,34,35,36,37,38,39,40,41,42])
print(a)
print(a.ndim)

[31 32 33 34 35 36 37 38 39 40 41 42]
1


In [31]:
a1=a.reshape(4,3)
print(a1)
print(a1.ndim)

[[31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]]
2


In [33]:
#converting 1D into 3D
a2=a.reshape(2,2,3)
print(a2)
print(a2.ndim)

[[[31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]]]
3


In [34]:
#horizontal stacking (column wise)
print(b)

[[24 25 26 27]
 [54 55 57 59]]


In [35]:
b1=np.array([[61,62,63],[64,65,66]])
b2=np.hstack((b,b1))
print(b2)

[[24 25 26 27 61 62 63]
 [54 55 57 59 64 65 66]]


In [39]:
print(b)
print(b1)
print(b2)

[[24 25 26 27]
 [54 55 57 59]]
[[61 62 63]
 [64 65 66]]
[[24 25 26 27 61 62 63]
 [54 55 57 59 64 65 66]]


In [43]:
#vertical stacking (row wise)
a=np.array([1,2,3])
a1=np.array([4,5,6])
a2=np.vstack((a,a1))
print(a2)

[[1 2 3]
 [4 5 6]]


In [46]:
#arithmetic operations
#adding
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
y=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
print(x)
print("-"*10)
print(y)
print("-"*10)
print(x+y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
----------
[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]


In [47]:
#subracting
print(y-x)

[[[12 12 12]
  [12 12 12]]

 [[12 12 12]
  [12 12 12]]]


In [48]:
#multiplying
print(x*y)

[[[ 13  28  45]
  [ 64  85 108]]

 [[133 160 189]
  [220 253 288]]]


In [49]:
#division
print(y/x)

[[[13.          7.          5.        ]
  [ 4.          3.4         3.        ]]

 [[ 2.71428571  2.5         2.33333333]
  [ 2.2         2.09090909  2.        ]]]


In [50]:
print(x**y)

[[[          1       16384    14348907]
  [          0 -1564725563  1159987200]]

 [[  442181591           0  1914644777]
  [-1304428544  -122979837           0]]]


In [51]:
#scalar arithmetic operations
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
#adding
print(x+2)
print("-"*20)
#subtract
print(x-2)
print("-"*20)
#multiplication
print(x*2)
print("-"*20)
#division
print(x/2)
print("-"*20)
#power operations
print(x**2)

[[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]
--------------------
[[[-1  0  1]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 8  9 10]]]
--------------------
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
--------------------
[[[0.5 1.  1.5]
  [2.  2.5 3. ]]

 [[3.5 4.  4.5]
  [5.  5.5 6. ]]]
--------------------
[[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]


In [54]:
#elementary mathematical functions
#trigonometric functions
print(np.sin(x))
print("-"*20)
print(np.cos(x))
print("-"*20)
print(np.tan(x))
print("-"*20)
print("-"*40)
#inverse trigonometric functions
print(np.arcsin(x))
print("-"*20)
print(np.arccos(x))
print("-"*20)
print(np.arctan(x))
print("-"*20)
print("-"*40)
#hyperbolic functions
print(np.sinh(x))
print("-"*20)
print(np.cosh(x))
print("-"*20)
print(np.tanh(x))
print("-"*20)
print("-"*40)
#inverse hyperbolic functions
print(np.arcsinh(x))
print("-"*20)
print(np.arccosh(x))
print("-"*20)
print(np.arctanh(x))
print("-"*20)
print("-"*40)
#square root
print(np.sqrt(x))
print("-"*40)
#exponential 
print(np.exp(x))
print("-"*40)
#logarithms
print(np.log(x))
print("-"*20)
print(np.log2(x))
print("-"*20)
print(np.log10(x))
print("-"*40)


[[[ 0.84147098  0.90929743  0.14112001]
  [-0.7568025  -0.95892427 -0.2794155 ]]

 [[ 0.6569866   0.98935825  0.41211849]
  [-0.54402111 -0.99999021 -0.53657292]]]
--------------------
[[[ 0.54030231 -0.41614684 -0.9899925 ]
  [-0.65364362  0.28366219  0.96017029]]

 [[ 0.75390225 -0.14550003 -0.91113026]
  [-0.83907153  0.0044257   0.84385396]]]
--------------------
[[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
  [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01]]

 [[ 8.71447983e-01 -6.79971146e+00 -4.52315659e-01]
  [ 6.48360827e-01 -2.25950846e+02 -6.35859929e-01]]]
--------------------
----------------------------------------
[[[1.57079633        nan        nan]
  [       nan        nan        nan]]

 [[       nan        nan        nan]
  [       nan        nan        nan]]]
--------------------
[[[ 0. nan nan]
  [nan nan nan]]

 [[nan nan nan]
  [nan nan nan]]]
--------------------
[[[0.78539816 1.10714872 1.24904577]
  [1.32581766 1.37340077 1.40564765]]

 [[1.42889927 1.44

<ipython-input-54-f6b601053de0>:11: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
<ipython-input-54-f6b601053de0>:13: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))
<ipython-input-54-f6b601053de0>:31: RuntimeWarning: divide by zero encountered in arctanh
  print(np.arctanh(x))
<ipython-input-54-f6b601053de0>:31: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(x))


In [2]:
import numpy as np

In [4]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [5]:
#elementary mathematical functions
#trigonometric functions
print(np.sin(x))
print("-"*20)
print(np.cos(x))
print("-"*20)
print(np.tan(x))

[[[ 0.84147098  0.90929743  0.14112001]
  [-0.7568025  -0.95892427 -0.2794155 ]]

 [[ 0.6569866   0.98935825  0.41211849]
  [-0.54402111 -0.99999021 -0.53657292]]]
--------------------
[[[ 0.54030231 -0.41614684 -0.9899925 ]
  [-0.65364362  0.28366219  0.96017029]]

 [[ 0.75390225 -0.14550003 -0.91113026]
  [-0.83907153  0.0044257   0.84385396]]]
--------------------
[[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
  [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01]]

 [[ 8.71447983e-01 -6.79971146e+00 -4.52315659e-01]
  [ 6.48360827e-01 -2.25950846e+02 -6.35859929e-01]]]


In [6]:
#inverse trigonometric functions
print(np.arcsin(x))
print("-"*20)
print(np.arccos(x))
print("-"*20)
print(np.arctan(x))

[[[1.57079633        nan        nan]
  [       nan        nan        nan]]

 [[       nan        nan        nan]
  [       nan        nan        nan]]]
--------------------
[[[ 0. nan nan]
  [nan nan nan]]

 [[nan nan nan]
  [nan nan nan]]]
--------------------
[[[0.78539816 1.10714872 1.24904577]
  [1.32581766 1.37340077 1.40564765]]

 [[1.42889927 1.44644133 1.46013911]
  [1.47112767 1.48013644 1.48765509]]]


<ipython-input-6-c4545f34208f>:2: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
<ipython-input-6-c4545f34208f>:4: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [7]:
#hyperbolic functions
print(np.sinh(x))
print("-"*20)
print(np.cosh(x))
print("-"*20)
print(np.tanh(x))

[[[1.17520119e+00 3.62686041e+00 1.00178749e+01]
  [2.72899172e+01 7.42032106e+01 2.01713157e+02]]

 [[5.48316123e+02 1.49047883e+03 4.05154190e+03]
  [1.10132329e+04 2.99370708e+04 8.13773957e+04]]]
--------------------
[[[1.54308063e+00 3.76219569e+00 1.00676620e+01]
  [2.73082328e+01 7.42099485e+01 2.01715636e+02]]

 [[5.48317035e+02 1.49047916e+03 4.05154203e+03]
  [1.10132329e+04 2.99370709e+04 8.13773957e+04]]]
--------------------
[[[0.76159416 0.96402758 0.99505475]
  [0.9993293  0.9999092  0.99998771]]

 [[0.99999834 0.99999977 0.99999997]
  [1.         1.         1.        ]]]


In [8]:
#inverse hyperbolic functions
print(np.arcsinh(x))
print("-"*20)
print(np.arccosh(x))
print("-"*20)
print(np.arctanh(x))

[[[0.88137359 1.44363548 1.81844646]
  [2.09471255 2.31243834 2.49177985]]

 [[2.64412076 2.77647228 2.89344399]
  [2.99822295 3.0931022  3.17978544]]]
--------------------
[[[0.         1.3169579  1.76274717]
  [2.06343707 2.29243167 2.47788873]]

 [[2.63391579 2.76865938 2.88727095]
  [2.99322285 3.0889699  3.17631318]]]
--------------------
[[[inf nan nan]
  [nan nan nan]]

 [[nan nan nan]
  [nan nan nan]]]


<ipython-input-8-a31d6815e24f>:6: RuntimeWarning: divide by zero encountered in arctanh
  print(np.arctanh(x))
<ipython-input-8-a31d6815e24f>:6: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(x))


In [9]:
#square root
print(np.sqrt(x))
#exponential 
print(np.exp(x))

[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]]

 [[2.64575131 2.82842712 3.        ]
  [3.16227766 3.31662479 3.46410162]]]
[[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [5.45981500e+01 1.48413159e+02 4.03428793e+02]]

 [[1.09663316e+03 2.98095799e+03 8.10308393e+03]
  [2.20264658e+04 5.98741417e+04 1.62754791e+05]]]


In [10]:
#logarithms
print(np.log(x))
print("-"*20)
print(np.log2(x))
print("-"*20)
print(np.log10(x))

[[[0.         0.69314718 1.09861229]
  [1.38629436 1.60943791 1.79175947]]

 [[1.94591015 2.07944154 2.19722458]
  [2.30258509 2.39789527 2.48490665]]]
--------------------
[[[0.         1.         1.5849625 ]
  [2.         2.32192809 2.5849625 ]]

 [[2.80735492 3.         3.169925  ]
  [3.32192809 3.45943162 3.5849625 ]]]
--------------------
[[[0.         0.30103    0.47712125]
  [0.60205999 0.69897    0.77815125]]

 [[0.84509804 0.90308999 0.95424251]
  [1.         1.04139269 1.07918125]]]


In [11]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
#NumPy Aggregate and Statistical operations
print(np.mean(x))    #arithmetic mean
print(np.std(x))     #standard deviation
print(np.var(x))     #variance
print(np.sum(x))     #sum
print(np.prod(x))     #product


6.5
3.452052529534663
11.916666666666666
78
479001600


In [13]:
print(np.cumsum(x)) #cumulative sum
print(np.cumprod(x))  #cumulative product
print(np.min(x))    #minimum of the array
print(np.max(x))    #maximum of the array

[ 1  3  6 10 15 21 28 36 45 55 66 78]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]
1
12


In [14]:
print(np.argmin(x))  #indices of the minimum values
print(np.argmax(x))  #indices of the maximum values
print(np.all(x))      #Test whether all array elements along a given axis evaluate to True.
print(np.any(x))     #Test whether any array element along a given axis evaluates to True.

0
11
True
True


In [16]:
#diagonal matrix with common values and full of zeros
a=np.matrix([1,2,3,4])
d=np.diag(a)
print(d)

[1]


In [20]:
#diagonal matrix with common values and full of zeros
a=np.array([1,2,3,4,5,6])
d=np.diag(a)
print(d)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [21]:
#identity matrix
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
