In [1]:
import numpy as np

In [2]:
a=np.array(9)
print(a)

9


In [1]:
#importing numpy
import numpy as np

In [2]:
#creating zero dimensional array
a=np.array(6)
print(a)
print("number of dimensions", a.ndim)

6
number of dimensions 0


In [3]:
#creating one dimensional array
b=np.array([11,12,13])
print(b)
print("number of dimensions", b.ndim)

[11 12 13]
number of dimensions 1


In [4]:
#creating two dimensional arrays
c=np.array([[11,12,13],[14,15,16]])
print(c)
print("number of dimensions", c.ndim)

[[11 12 13]
 [14 15 16]]
number of dimensions 2


In [6]:
#creating three dimensional arrays
d=np.array([[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]])
print(d)
print("number of dimensions", d.ndim)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]
number of dimensions 3


In [7]:
#creating high dimensional arrays
e=np.array([50,51,52,53,54,55,56,57,58,59], ndmin=12)
print(e)
print("number of dimensions", e.ndim)

[[[[[[[[[[[[50 51 52 53 54 55 56 57 58 59]]]]]]]]]]]]
number of dimensions 12


In [9]:
#accessing array elements
print(e[0])

[[[[[[[[[[[50 51 52 53 54 55 56 57 58 59]]]]]]]]]]]


In [10]:
print(d[0,1,1])

15


In [11]:
print(d[0,1,2]+d[1,0,0])

33


In [15]:
print(c[1,-1])

16


In [16]:
print(b[0:-1]) 
#slicing the array

[11 12]


In [17]:
print(c[1:1:1])

[]


In [18]:
#finding datatypes 
print(d.dtype)

int32


In [19]:
print(b.dtype)

int32


In [22]:
f=np.array(['banana','apple','mango','orange'])
print(f)
print(f.ndim)
print(f.dtype)

['banana' 'apple' 'mango' 'orange']
1
<U6


In [23]:
g=np.array(['red','blue','green','yellow'], dtype='S')
print(g)
print(g.ndim)
print(g.dtype)

[b'red' b'blue' b'green' b'yellow']
1
|S6
